[paas_classic.services]


[paas_classic.services.ServiceInstances]
name = 'ServiceInstances'
title = 'Service Instances'
api_collection_name = 'database'
api_version = '1.1'

[paas_classic.services.SSHKeys]
name = 'SSHKeys'
title = 'SSH Keys'
api_collection_name = 'database'
api_version = '1.1'
