# -*- coding: utf-8 -*-

"""
#@Filename : security_rules_data
#@Date : [8/8/2018 12:15 PM]
#@Poject: gc3-query
#@AUTHOR : emharris

~~~~~~~~~~~~~~~~

<DESCR SHORT>

<DESCR>
"""

################################################################################
## Standard Library Imports
import sys, os

################################################################################
## Third-Party Imports
from dataclasses import dataclass

################################################################################
## Project Imports
from gc3_query.lib import *

_debug, _info, _warning, _error, _critical = get_logging(name=__name__)

secrules = [{'name': '/Compute-587626604/default/egress',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/default/egress',
             'description': 'Default egress Network Security Rule', 'tags': [], 'acl': '/Compute-587626604/default',
             'flowDirection': 'egress', 'srcVnicSet': '/Compute-587626604/default', 'dstVnicSet': None, 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_p2admin_ahttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_p2admin_ahttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_admin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ahttps'], 'enabledFlag': False},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/sys_infra2wls_admin_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/sys_infra2wls_admin_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls_infraadmin',
             'srcIpAddressPrefixSets': ['/oracle/public/paas-infra'], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_infraadmin_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_infraadmin_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_infraadmin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_infraadmin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True}, {'name': '/Compute-587626604/default/ingress',
                                                                                      'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/default/ingress',
                                                                                      'description': 'Default ingress Network Security Rule',
                                                                                      'tags': [], 'acl': '/Compute-587626604/default',
                                                                                      'flowDirection': 'ingress',
                                                                                      'srcVnicSet': '/Compute-587626604/default',
                                                                                      'dstVnicSet': '/Compute-587626604/default',
                                                                                      'srcIpAddressPrefixSets': [],
                                                                                      'dstIpAddressPrefixSets': [], 'secProtocols': [],
                                                                                      'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls2db_dbport',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls2db_dbport',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/dbport'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_p2ms_chttp',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_p2ms_chttp',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/chttp'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_p2otd_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_p2otd_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls_infraadmin_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls_infraadmin_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls_infraadmin',
             'dstVnicSet': None, 'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls_infraadmin_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls_infraadmin_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls_infraadmin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls_infraadmin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_acl_default',
             'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_acl_default',
             'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/sys_infra2otd_admin_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/sys_infra2otd_admin_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_infraadmin',
             'srcIpAddressPrefixSets': ['/oracle/public/paas-infra'], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_infraadmin_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_infraadmin_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_acl_default',
             'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_infraadmin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_infraadmin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_httpssl',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_httpssl',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/httpssl'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_http',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_http',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/http'], 'enabledFlag': False},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_dbconsole',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_dbconsole',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/dbconsole'], 'enabledFlag': False},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_p2otd_ahttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_p2otd_ahttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ahttps'], 'enabledFlag': False},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls2db_dbport',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls2db_dbport',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/dbport'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_sys_ms2db_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_sys_ms2db_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/ora_otd2ms_chttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/ora_otd2ms_chttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/chttps'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_p2otd_ahttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_p2otd_ahttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ahttps'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_admin_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_admin_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_admin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_admin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_p2ms_chttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_p2ms_chttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/chttps'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_sys_ms2db_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_sys_ms2db_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/sys_wls2otd_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/sys_wls2otd_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_wls_infraadmin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_infraadmin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/ora_otd2ms_chttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/ora_otd2ms_chttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/chttps'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_infraadmin_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_infraadmin_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_infraadmin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_infraadmin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_dbexpress',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_dbexpress',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/dbexpress'], 'enabledFlag': False},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_trusted_hosts_dblistener',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_trusted_hosts_dblistener',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db',
             'srcIpAddressPrefixSets': [
                 '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_trusted_hosts_dblistener'],
             'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/dblistener'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/sys_infra2wls_admin_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/sys_infra2wls_admin_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls_infraadmin',
             'srcIpAddressPrefixSets': ['/oracle/public/paas-infra'], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/ora_otd2ms_chttp',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/ora_otd2ms_chttp',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/chttp'], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db',
             'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_http',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_http',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/http'], 'enabledFlag': False},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_httpssl',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_httpssl',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/httpssl'], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_dbconsole',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_dbconsole',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/dbconsole'], 'enabledFlag': False},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/sys_infra2db_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/sys_infra2db_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
             'srcIpAddressPrefixSets': ['/oracle/public/paas-infra'], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_infraadmin_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_infraadmin_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_infraadmin',
             'dstVnicSet': None, 'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_p2otd_chttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_p2otd_chttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/chttps'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_admin_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_admin_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_admin', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_httpssl',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_httpssl',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/httpssl'], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_dbconsole',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_dbconsole',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/dbconsole'], 'enabledFlag': False},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
             'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_trusted_hosts_dblistener',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_trusted_hosts_dblistener',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
             'srcIpAddressPrefixSets': [
                 '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_trusted_hosts_dblistener'],
             'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/dblistener'], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_dblistener',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_p2_dblistener',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/dblistener'],
             'enabledFlag': False}, {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/sys_infra2db_ssh',
                                     'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/sys_infra2db_ssh',
                                     'description': None, 'tags': [],
                                     'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_acl_default',
                                     'flowDirection': 'ingress', 'srcVnicSet': None,
                                     'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ora_db',
                                     'srcIpAddressPrefixSets': ['/oracle/public/paas-infra'], 'dstIpAddressPrefixSets': [],
                                     'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3naaccvsb755/db_1/ssh'],
                                     'enabledFlag': True}, {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_secrule_01',
                                                            'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_secrule_01',
                                                            'description': 'NTAG Digital Evidence Management', 'tags': ['ntagdevm'],
                                                            'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_acl_01',
                                                            'flowDirection': 'egress',
                                                            'srcVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_vnicset_01',
                                                            'dstVnicSet': None, 'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
                                                            'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_secrule_02',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_secrule_02',
             'description': 'NTAG Digital Evidence Management', 'tags': ['ntagdevm'],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_acl_01', 'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_vnicset_01', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_pfset_01'],
             'secProtocols': ['/oracle/public/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_http',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_http',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/http'], 'enabledFlag': False},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_dbexpress',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_dbexpress',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/dbexpress'], 'enabledFlag': False},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_secrule_02',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_secrule_02',
             'description': 'NAAC CVS Sandbox', 'tags': ['naaccvsb'],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_acl_01', 'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_vnicset_01', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_pfset_01'],
             'secProtocols': ['/oracle/public/https', '/oracle/public/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_secrule_03',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_secrule_03',
             'description': 'NAAC CVS Sandbox', 'tags': ['naaccvsb'],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_acl_01', 'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': None, 'srcIpAddressPrefixSets': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_pfset_01'],
             'dstIpAddressPrefixSets': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_pfset_01'], 'secProtocols': [],
             'enabledFlag': True}, {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_secrule_03',
                                    'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_secrule_03',
                                    'description': 'NTAG Digital Evidence Management', 'tags': ['ntagdevm'],
                                    'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_acl_01', 'flowDirection': 'ingress',
                                    'srcVnicSet': None, 'dstVnicSet': None,
                                    'srcIpAddressPrefixSets': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_pfset_01'],
                                    'dstIpAddressPrefixSets': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/ntagdevm_pfset_01'],
                                    'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_secrule_01',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_secrule_01',
             'description': 'NAAC CVS Sandbox', 'tags': ['naaccvsb'],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_acl_01', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/naaccvsb_vnicset_01', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/sys_infra2db_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/sys_infra2db_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db',
             'srcIpAddressPrefixSets': ['/oracle/public/paas-infra'], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_infraadmin_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_infraadmin_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_infraadmin',
             'dstVnicSet': None, 'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_p2otd_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_p2otd_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_dblistener',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_p2_dblistener',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/dblistener'],
             'enabledFlag': False}, {'name': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db_egress_all',
                                     'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db_egress_all',
                                     'description': None, 'tags': [],
                                     'acl': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_acl_default',
                                     'flowDirection': 'egress',
                                     'srcVnicSet': '/Compute-587626604/dhiru.vallabhbhai@oracle.com/dbaas/gc3ntagdevm713/db_1/ora_db',
                                     'dstVnicSet': None, 'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [],
                                     'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/sys_infra2otd_admin_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/sys_infra2otd_admin_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd_infraadmin',
             'srcIpAddressPrefixSets': ['/oracle/public/paas-infra'], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/ora_otd2ms_chttp',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/ora_otd2ms_chttp',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [], 'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/chttp'],
             'enabledFlag': True}, {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/ora_otd2ms_chttps',
                                    'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/ora_otd2ms_chttps',
                                    'description': None, 'tags': [],
                                    'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default',
                                    'flowDirection': 'ingress',
                                    'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd',
                                    'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms',
                                    'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
                                    'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/chttps'],
                                    'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_admin_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_admin_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_admin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_admin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls_infraadmin_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls_infraadmin_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls_infraadmin',
             'dstVnicSet': None, 'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/ora_otd2ms_chttp',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/ora_otd2ms_chttp',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/chttp'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_p2admin_ahttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_p2admin_ahttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_admin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ahttps'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_p2admin_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_p2admin_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_admin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls_infraadmin_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls_infraadmin_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls_infraadmin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_wls_infraadmin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_admin_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_admin_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_acl_default',
             'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/wls/ora_admin', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls_infraadmin_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls_infraadmin_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls_infraadmin',
             'dstVnicSet': None, 'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_p2ms_chttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_p2ms_chttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/chttps'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_p2ms_chttp',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_p2ms_chttp',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/chttp'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_admin_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_admin_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_admin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_admin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_sys_ms2db_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_sys_ms2db_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_p2admin_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_p2admin_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_admin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_dbexpress',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_dbexpress',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/dbexpress'], 'enabledFlag': False},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_trusted_hosts_dblistener',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_trusted_hosts_dblistener',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db',
             'srcIpAddressPrefixSets': [
                 '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_trusted_hosts_dblistener'],
             'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/dblistener'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_ms',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_p2admin_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_p2admin_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ora_admin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/wls/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/sys_infra2wls_admin_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/sys_infra2wls_admin_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls_infraadmin',
             'srcIpAddressPrefixSets': ['/oracle/public/paas-infra'], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/sys_infra2otd_admin_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/sys_infra2otd_admin_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd_infraadmin',
             'srcIpAddressPrefixSets': ['/oracle/public/paas-infra'], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_p2otd_ahttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_p2otd_ahttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/JaaS/gc3oladdoam726/lb/ahttps'], 'enabledFlag': False},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_p2otd_chttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_p2otd_chttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/chttps'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls2db_dbport',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls2db_dbport',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/dbport'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_dblistener',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_p2_dblistener',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/ora_db',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/dbaas/gc3oladdoam725/db_1/dblistener'], 'enabledFlag': False},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_p2otd_ssh',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_p2otd_ssh',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_acl_default',
             'flowDirection': 'ingress', 'srcVnicSet': None,
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ssh'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_infraadmin_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_infraadmin_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_acl_default',
             'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/APICS/gc3oladdoam728/1/lb/ora_otd_infraadmin',
             'dstVnicSet': None, 'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_p2admin_ahttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_p2admin_ahttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_admin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ahttps'], 'enabledFlag': False},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls_infraadmin_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls_infraadmin_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls_infraadmin',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_wls_infraadmin',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_p2otd_chttps',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_p2otd_chttps',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': None, 'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/ora_otd',
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [],
             'secProtocols': ['/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/lb/chttps'], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_admin_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_admin_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_admin', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms_ingress_self',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms_ingress_self',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'ingress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms',
             'dstVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms', 'srcIpAddressPrefixSets': [],
             'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True},
            {'name': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms_egress_all',
             'uri': 'https://compute.uscom-central-1.oraclecloud.com:443/network/v1/secrule/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms_egress_all',
             'description': None, 'tags': [],
             'acl': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_acl_default', 'flowDirection': 'egress',
             'srcVnicSet': '/Compute-587626604/manjunath.udupa@oracle.com/paas/SOA/gc3oladdoam727/wls/ora_ms', 'dstVnicSet': None,
             'srcIpAddressPrefixSets': [], 'dstIpAddressPrefixSets': [], 'secProtocols': [], 'enabledFlag': True}]
