---
swagger: '2.0'
info:
  version: 18.1.2-20180126.052521
  description: An account is used in Compute Classic to store credentials that must
    be used to access another service. For example, you use an account to define the
    credentials and other details of the Oracle Cloud Infrastructure Object Storage
    Classic instance in which you store machine images.<p>You can view accounts using
    the HTTP requests listed below.
  title: Accounts
schemes:
- https
consumes:
- application/oracle-compute-v3+json
- application/oracle-compute-v3+directory+json
produces:
- application/oracle-compute-v3+json
- application/oracle-compute-v3+directory+json
paths:
  "/account/":
    get:
      tags:
      - Accounts
      summary: Retrieve Names of Containers
      description: 'Retrieves the names of containers that contain objects that you
        can access. You can use this information to construct the multipart name of
        an object.<p><b>Required Role: </b>To complete this task, you must have the
        <code>Compute_Monitor</code> or <code>Compute_Operations</code> role. If this
        role isn''t assigned to you or you''re not sure, then ask your system administrator
        to ensure that the role is assigned to you in Oracle Cloud My Services. See
        <a target="_blank" href="http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6">Modifying
        User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>.'
      operationId: discoverRootAccount
      responses:
        '200':
          headers:
            set-cookie:
              type: string
              description: The cookie value is returned if the session is extended
          description: OK. See <a class="xref" href="Status%20Codes.html">Status Codes</a>
            for information about other possible HTTP status codes.
          schema:
            "$ref": "#/definitions/Account-discover-response"
      consumes:
      - application/oracle-compute-v3+json
      produces:
      - application/oracle-compute-v3+directory+json
      parameters:
      - name: Cookie
        in: header
        type: string
        description: 'The Cookie: header must be included with every request to the
          service. It must be set to the value of the set-cookie header in the response
          received to the POST /authenticate/ call.'
  "/account/{container}":
    get:
      tags:
      - Accounts
      summary: Retrieve Names of all Accounts and Subcontainers in a Container
      description: 'Retrieves names of all the accounts in the specified container.<p><b>Required
        Role: </b>To complete this task, you must have the <code>Compute_Monitor</code>
        or <code>Compute_Operations</code> role. If this role isn''t assigned to you
        or you''re not sure, then ask your system administrator to ensure that the
        role is assigned to you in Oracle Cloud My Services. See <a target="_blank"
        href="http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6">Modifying
        User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>.'
      operationId: discoverAccount
      responses:
        '200':
          headers:
            set-cookie:
              type: string
              description: The cookie value is returned if the session is extended
          description: OK. See <a class="xref" href="Status%20Codes.html">Status Codes</a>
            for information about other possible HTTP status codes.
          schema:
            "$ref": "#/definitions/Account-discover-response"
      consumes:
      - application/oracle-compute-v3+json
      produces:
      - application/oracle-compute-v3+directory+json
      parameters:
      - name: container
        in: path
        description: "<p>Specify <code>/Compute-<i>identityDomain</i></code> to retrieve
          the names of objects that you can access."
        required: true
        type: string
      - name: Cookie
        in: header
        type: string
        description: 'The Cookie: header must be included with every request to the
          service. It must be set to the value of the set-cookie header in the response
          received to the POST /authenticate/ call.'
  "/account/{container}/":
    get:
      tags:
      - Accounts
      summary: Retrieve Details of all Accounts in a Container
      description: 'Retrieves details of the accounts that are in the specified identity
        domain. You can use this HTTP request to get details of the account that you
        must specify while creating a machine image.<p><b>Required Role: </b>To complete
        this task, you must have the <code>Compute_Monitor</code> or <code>Compute_Operations</code>
        role. If this role isn''t assigned to you or you''re not sure, then ask your
        system administrator to ensure that the role is assigned to you in Oracle
        Cloud My Services. See <a target="_blank" href="http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6">Modifying
        User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>.'
      operationId: listAccount
      responses:
        '200':
          headers:
            set-cookie:
              type: string
              description: The cookie value is returned if the session is extended
          description: OK. See <a class="xref" href="Status%20Codes.html">Status Codes</a>
            for information about other possible HTTP status codes.
          schema:
            "$ref": "#/definitions/Account-list-response"
      consumes:
      - application/oracle-compute-v3+json
      produces:
      - application/oracle-compute-v3+json
      parameters:
      - name: container
        in: path
        description: "<code>Compute-<em>identity_domain</em></code><p>For example:
          <code>Compute-acme</code>."
        required: true
        type: string
      - name: Cookie
        in: header
        type: string
        description: 'The Cookie: header must be included with every request to the
          service. It must be set to the value of the set-cookie header in the response
          received to the POST /authenticate/ call.'
  "/account/{name}":
    get:
      tags:
      - Accounts
      summary: Retrieve Details of an Account
      description: 'Retrieves details of the specified account.<p><b>Required Role:
        </b>To complete this task, you must have the <code>Compute_Monitor</code>
        or <code>Compute_Operations</code> role. If this role isn''t assigned to you
        or you''re not sure, then ask your system administrator to ensure that the
        role is assigned to you in Oracle Cloud My Services. See <a target="_blank"
        href="http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6">Modifying
        User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>.'
      operationId: getAccount
      responses:
        '200':
          headers:
            set-cookie:
              type: string
              description: The cookie value is returned if the session is extended
          description: OK. See <a class="xref" href="Status%20Codes.html">Status Codes</a>
            for information about other possible HTTP status codes.
          schema:
            "$ref": "#/definitions/Account-response"
      consumes:
      - application/oracle-compute-v3+json
      produces:
      - application/oracle-compute-v3+json
      parameters:
      - name: name
        in: path
        description: 'Two-part name of the account: <code>/Compute-<em>identity_domain</em>/default</code>
          or <code>/Compute-<em>identity_domain</em>/cloud_storage</code>'
        required: true
        type: string
      - name: Cookie
        in: header
        type: string
        description: 'The Cookie: header must be included with every request to the
          service. It must be set to the value of the set-cookie header in the response
          received to the POST /authenticate/ call.'
definitions:
  Account-discover-response:
    title: Account-discover-response
    "x-model": Account-discover-response
    type: object
    properties:
      result:
        items:
          type: string
        type: array
  Account-list-response:
    title: Account-list-response
    "x-model": "Account-list-response"
    type: object
    properties:
      result:
        type: array
        title: Response Array
        description: Response array
        items:
          "$ref": "#/definitions/Account-response"
  Account-response:
    title: Account-response
    description: Account-response
    "x-model": Account-response
    type: object
    properties:
      accounttype:
        type: string
        description: Account Type for this account
        "x-nullable": true
      credentials:
        additionalProperties:
          type: object
          "x-nullable": true
        type: object
        "x-nullable": true
        description: Credentials specific to the account, which may include a username,
          password or certificate. The credentials are not returned.
      description:
        type: string
        description: Description of this account.
        "x-nullable": true
      name:
        type: string
        "x-nullable": true
        description: 'Two-part name of the account: <code>/Compute-<em>identity_domain</em>/default</code>
          or <code>/Compute-<em>identity_domain</em>/cloud_storage</code>'
      uri:
        type: string
        "x-nullable": true
        description: Uniform Resource Identifier
      objectproperties:
        type: object
        "x-nullable": true
        description: Properties to be applied to specific objects created using this account
        additionalProperties:
          type: object
          "x-nullable": true
tags:
- name: Accounts
  description: An account is used in Compute Classic to store credentials that must
    be used to access another service. For example, you use an account to define the
    credentials and other details of the Oracle Cloud Infrastructure Object Storage
    Classic instance in which you store machine images.<p>You can view accounts using
    the HTTP requests listed below.
