[open_api]
__doc__ = "API catalog"
open_api_spec_base: Path = 'etc/open_api'

[open_api.open_api_spec_catalog]
name  = 'open_api_spec_catalog'
api_catalog_dir: Path =  'opt/open_api_catalog'
json_export_indent_spaces: int = 2
archive_dir: Path = 'archive'
archive_file_format: fstr = '{name}_{version}.json'

[open_api.export]
export_dir: Path =  'var/open_api_catalog'

[open_api.open_api_spec_overlay]
spec_overlay_format = 'toml'

[open_api.iaas_classic]

[open_api.formats]

[open_api.formats.oc_datetime]
format = 'oc-datetime'
description = 'Converts string:date-time <=> python Maya object'

[open_api.formats.paas_date_time]
format = 'paas-date-time'
description = 'Converts string:date-time <=> python Maya object'

[open_api.formats.json_bool]
format = 'json-bool'
description = 'Converts "true" and "false" to/from equivalent booleans.'

[open_api.formats.bool_in_str]
format = 'bool-in-str'
description = 'Converts "true" and "false" to/from equivalent booleans.'

[open_api.formats.date]
format = 'date'
description = 'Converts [wire]string:date <=> python datetime.date'

[open_api.formats.date_time]
format = 'date-time'
description = 'Converts string:date-time <=> python datetime.datetime'
