[user]
first_name = 'Eric'
last_name = 'Harris'
email: Email = 'eric.harris@oracle.com'
cloud_username: Email = 'eric.harris@oracle.com'
os_username = 'eharris'
global_username = 'eharris_us'
windows_home_directory = 'C:\Users\eharris'
linux_home_directory = '/home/eharris'
password_storage = 'keyring'
default_idm_domain = 'gc30003'
use_proxy = false
windows_editors = ['sublime_text', 'gvim', 'notepad++', 'notepad']
linux_editors = ['sublime_text', 'gvim', 'vim', 'vi']



