schemes = [ "https",]
[definitions.SecRule-response.properties.dst_is_ip]
type = "boolean"
description = "<p>Indicates whether the security rule destination is an IP (set to <code>false</code>) or disabled (<code>true</code>)."
[definitions.SecRule-response.properties.src_is_ip]
type = "boolean"
description = "<p>Indicates whether the security rule source is an IP (set to <code>false</code>) or disabled (<code>true</code>)."
