swagger = "2.0"
schemes = [ "https",]
consumes = [ "application/oracle-compute-v3+json", "application/oracle-compute-v3+directory+json",]
produces = [ "application/oracle-compute-v3+json", "application/oracle-compute-v3+directory+json",]
[[tags]]
name = "IPAddressReservations"
description = "A reservation of a NAT IPv4 address, which can be associated to one or more virtual NICs for routing outside of an IP network / IP network exchange using NAT."

[info]
version = "18.1.2-20180126.052521"
description = "A reservation of a NAT IPv4 address, which can be associated to one or more virtual NICs for routing outside of an IP network / IP network exchange using NAT."
title = "IPAddressReservations"

[definitions.DailyWeeklyInterval]
[[definitions.DailyWeeklyInterval.allOf]]
"$ref" = "#/definitions/Interval"

[[definitions.DailyWeeklyInterval.allOf]]
type = "object"
description = "Backup Interval running once a day on certain days of the week"

[definitions.DailyWeeklyInterval.allOf.properties.userTimeZone]
type = "string"
description = "Any IANA time zone. e.g: America/Los_Angeles"
[definitions.DailyWeeklyInterval.allOf.properties.timeOfDay]
pattern = "([01]?[0-9]|2[0-3]):[0-5][0-9]"
type = "string"
description = "Time of the day to run a backup"
[definitions.DailyWeeklyInterval.allOf.properties.daysOfWeek]
type = "array"
description = "Days of the week to run a backup"
[definitions.DailyWeeklyInterval.allOf.properties.daysOfWeek.items]
enum = [ "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY",]
type = "string"

[definitions.HourlyInterval]
[[definitions.HourlyInterval.allOf]]
"$ref" = "#/definitions/Interval"

[[definitions.HourlyInterval.allOf]]
type = "object"
description = "Backup Interval running every X hours"

[definitions.HourlyInterval.allOf.properties.hourlyInterval]
type = "integer"
description = "Hours to wait before starting the next backup"
format = "int32"

[definitions.Interval]
x-oneOf-instructions = "Provide one of the valid object representations documented here.  For more information about oneOf see http://json-schema.org/latest/json-schema-validation.html#anchor88"
type = "object"
description = "There are two kinds of Intervals. Each Interval has its own JSON format. Your Interval field should look like one of the following:<p><ul><li><code>\"interval\":{\"Hourly\":{\"hourlyInterval\":2}}</code></li><li><code>{\"DailyWeekly\":{\"daysOfWeek\":[\"MONDAY\"],\"timeOfDay\":\"03:15\",\"userTimeZone\":\"America/Los_Angeles\"}}</code></li></ul><p>Days of the week is any day of the week fully capitalized (MONDAY, TUESDAY, etc). The user time zone is any IANA user timezone.  For example user time zones see <a href=\"https://en.wikipedia.org/wiki/IANA_time_zone_database\">List of IANA time zones</a>."

[definitions.IpAddressReservation-post-request]
required = [ "name",]
description = "The request body contains details of the IP address reservation that you want to create. "

[definitions.IpAddressReservation-put-request]
required = [ "name",]
description = "The request body contains details of the IP address reservation that you want to update. "

[paths."/network/v1/ipreservation/".post]
tags = [ "IPAddressReservations",]
summary = "Create an IP Address Reservation for IP Networks"
description = "Reserves a NAT IPv4 address, which you can associate with one or more virtual NICs for routing traffic outside an IP network or an IP network exchange using NAT.<p>To reserve an IP address for an instance that you have created in the flat network, see Create an IP Reservation.<p>Reserve an IP address from one of the following IP pools:<p>* A pool of public IP addresses. An IP address from this pool is accessible over the public Internet.<p>* A pool of cloud IP addresses. An IP address from this pool is accessible to other IP networks in the Oracle cloud. You can use these IP addresses to communicate with other Oracle services.<p>When you reserve an IP address from a specified IP pool, an IPv4 address is allocated for your use.<p>A public IP address or a cloud IP address can be associated with only one vNIC at a time. However, a single vNIC can have a maximum of two NAT IP addresses, one from each IP pool.<p>After reserving an IP address, you can and associate the IP address with a vNIC on your instance. See <a class=\"xref\" href=\"op-network-v1-ipassociation--post.html\">Create an IP Address Association</a>.<p><b>Required Role: </b>To complete this task, you must have the <code>Compute_Operations</code> role. If this role isn't assigned to you or you're not sure, then ask your system administrator to ensure that the role is assigned to you in Oracle Cloud My Services. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6\">Modifying User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>."
operationId = "addIPAddressReservation"
consumes = [ "application/oracle-compute-v3+json",]
produces = [ "application/oracle-compute-v3+json",]
[[paths."/network/v1/ipreservation/".post.parameters]]
name = "body"
in = "body"
required = true

[paths."/network/v1/ipreservation/".post.parameters.schema]
"$ref" = "#/definitions/IpAddressReservation-post-request"
[[paths."/network/v1/ipreservation/".post.parameters]]
name = "Cookie"
in = "header"
type = "string"
description = "The Cookie: header must be included with every request to the service. It must be set to the value of the set-cookie header in the response received to the POST /authenticate/ call."

[paths."/network/v1/ipreservation/{container}/".get]
tags = [ "IPAddressReservations",]
summary = "Retrieve Details of all IP Address Reservations in a Container"
description = "Retrieves details of the IP address reservations that are available in the specified container. This request is for IP address reservations used in IP networks.<p><b>Required Role: </b>To complete this task, you must have the <code>Compute_Operations</code> role. If this role isn't assigned to you or you're not sure, then ask your system administrator to ensure that the role is assigned to you in Oracle Cloud My Services. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6\">Modifying User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>."
operationId = "listIPAddressReservation"
consumes = [ "application/oracle-compute-v3+json",]
produces = [ "application/oracle-compute-v3+json",]
[[paths."/network/v1/ipreservation/{container}/".get.parameters]]
name = "container"
in = "path"
description = "<code>/Compute-<em>identity_domain</em>/<em>user</em></code> or <p><code>/Compute-<em>identity_domain</em></code>"
required = true
type = "string"

[[paths."/network/v1/ipreservation/{container}/".get.parameters]]
name = "Cookie"
in = "header"
type = "string"
description = "The Cookie: header must be included with every request to the service. It must be set to the value of the set-cookie header in the response received to the POST /authenticate/ call."

[paths."/network/v1/ipreservation/{name}".put]
tags = [ "IPAddressReservations",]
summary = "Update an IP Address Reservation Used in IP Networks"
description = "Updates the specified IP address reservation.<p><b>Required Role: </b>To complete this task, you must have the <code>Compute_Operations</code> role. If this role isn't assigned to you or you're not sure, then ask your system administrator to ensure that the role is assigned to you in Oracle Cloud My Services. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6\">Modifying User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>."
operationId = "updateIPAddressReservation"
consumes = [ "application/oracle-compute-v3+json",]
produces = [ "application/oracle-compute-v3+json",]
[[paths."/network/v1/ipreservation/{name}".put.parameters]]
name = "name"
in = "path"
description = "The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>)."
required = true
type = "string"

[[paths."/network/v1/ipreservation/{name}".put.parameters]]
name = "body"
in = "body"
required = true

[paths."/network/v1/ipreservation/{name}".put.parameters.schema]
"$ref" = "#/definitions/IpAddressReservation-put-request"
[[paths."/network/v1/ipreservation/{name}".put.parameters]]
name = "Cookie"
in = "header"
type = "string"
description = "The Cookie: header must be included with every request to the service. It must be set to the value of the set-cookie header in the response received to the POST /authenticate/ call."

[paths."/network/v1/ipreservation/{name}".delete]
tags = [ "IPAddressReservations",]
summary = "Delete an IP Address Reservation Used in IP Networks"
description = "Deletes the specified IP address reservation.<p><b>Required Role: </b>To complete this task, you must have the <code>Compute_Operations</code> role. If this role isn't assigned to you or you're not sure, then ask your system administrator to ensure that the role is assigned to you in Oracle Cloud My Services. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6\">Modifying User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>."
operationId = "deleteIPAddressReservation"
consumes = [ "application/oracle-compute-v3+json",]
produces = [ "application/oracle-compute-v3+json",]
[[paths."/network/v1/ipreservation/{name}".delete.parameters]]
name = "name"
in = "path"
description = "The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>)."
required = true
type = "string"

[[paths."/network/v1/ipreservation/{name}".delete.parameters]]
name = "Cookie"
in = "header"
type = "string"
description = "The Cookie: header must be included with every request to the service. It must be set to the value of the set-cookie header in the response received to the POST /authenticate/ call."

[paths."/network/v1/ipreservation/{name}".get]
tags = [ "IPAddressReservations",]
summary = "Retrieve Details of an IP Address Reservation Used in IP Networks"
description = "Retrieves details of the specified IP address reservation.<p><b>Required Role: </b>To complete this task, you must have the <code>Compute_Operations</code> role. If this role isn't assigned to you or you're not sure, then ask your system administrator to ensure that the role is assigned to you in Oracle Cloud My Services. See <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6\">Modifying User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>."
operationId = "getIPAddressReservation"
consumes = [ "application/oracle-compute-v3+json",]
produces = [ "application/oracle-compute-v3+json",]
[[paths."/network/v1/ipreservation/{name}".get.parameters]]
name = "name"
in = "path"
description = "The three-part name of the object (<code>/Compute-<em>identity_domain</em>/<em>user</em>/<em>object</em></code>)."
required = true
type = "string"

[[paths."/network/v1/ipreservation/{name}".get.parameters]]
name = "Cookie"
in = "header"
type = "string"
description = "The Cookie: header must be included with every request to the service. It must be set to the value of the set-cookie header in the response received to the POST /authenticate/ call."

[definitions.Interval.x-oneOf]
[[definitions.Interval.x-oneOf.oneOf]]
type = "object"

[definitions.Interval.x-oneOf.oneOf.properties.DailyWeekly]
[[definitions.Interval.x-oneOf.oneOf.properties.DailyWeekly.allOf]]
"$ref" = "#/definitions/DailyWeeklyInterval"

[[definitions.Interval.x-oneOf.oneOf.properties.DailyWeekly.allOf]]
type = "object"

[[definitions.Interval.x-oneOf.oneOf]]
type = "object"

[definitions.Interval.x-oneOf.oneOf.properties.Hourly]
[[definitions.Interval.x-oneOf.oneOf.properties.Hourly.allOf]]
"$ref" = "#/definitions/HourlyInterval"

[[definitions.Interval.x-oneOf.oneOf.properties.Hourly.allOf]]
type = "object"

[definitions.IpAddressReservation-list-response.properties.result]
type = "array"

[definitions.IpAddressReservation-post-request.properties.description]
type = "string"
description = "Description of the IP address reservation."

[definitions.IpAddressReservation-post-request.properties.ipAddressPool]
type = "string"
description = "The IP address pool from which you want to reserve an IP address. Specify one of the following values:<p>* <code>/oracle/public/public-ippool</code>: A pool of public IP addresses. An IP address from this pool is accessible over the public Internet.<p>* <code>/oracle/public/cloud-ippool</code>: A pool of cloud IP addresses. An IP address from this pool is accessible to other IP networks in the Oracle cloud. You can use these IP addresses to communicate with other Oracle services."

[definitions.IpAddressReservation-post-request.properties.name]
type = "string"
description = "The three-part name of the IP address reservation(/Compute-identity_domain/user/object).<p>Object names can contain only alphanumeric characters, hyphens, underscores, and periods. Object names are case-sensitive. When you specify the object name, ensure that an object of the same type and with the same name doesn't already exist. If such an object already exists, another object of the same type and with the same name won't be created and the existing object won't be updated."

[definitions.IpAddressReservation-post-request.properties.tags]
type = "array"
description = "Strings that you can use to tag the IP address reservation."

[definitions.IpAddressReservation-put-request.properties.description]
type = "string"
description = "Description of the IP address reservation."

[definitions.IpAddressReservation-put-request.properties.ipAddressPool]
type = "string"
description = "The IP address pool from which you want to reserve an IP address. Specify one of the following values:<p>* <code>/oracle/public/public-ippool</code>: A pool of public IP addresses. An IP address from this pool is accessible over the public Internet.<p>* <code>/oracle/public/cloud-ippool</code>: A pool of cloud IP addresses. An IP address from this pool is accessible to other IP networks in the Oracle cloud. You can use these IP addresses to communicate with other Oracle services."

[definitions.IpAddressReservation-put-request.properties.name]
type = "string"
description = "The three-part name of the IP address reservation(/Compute-identity_domain/user/object).<p>Object names can contain only alphanumeric characters, hyphens, underscores, and periods. Object names are case-sensitive. When you specify the object name, ensure that an object of the same type and with the same name doesn't already exist. If such an object already exists, another object of the same type and with the same name won't be created and the existing object won't be updated."

[definitions.IpAddressReservation-put-request.properties.tags]
type = "array"
description = "Strings that you can use to tag the IP address reservation."

[definitions.IpAddressReservation-response.properties.description]
type = "string"
description = "Description of the object."

[definitions.IpAddressReservation-response.properties.ipAddress]
type = "string"
description = "Reserved NAT IPv4 address from the IP address pool."

[definitions.IpAddressReservation-response.properties.ipAddressPool]
type = "string"
description = "Name of the IP address pool to reserve the NAT IP from."

[definitions.IpAddressReservation-response.properties.name]
type = "string"
description = "Name of the IP address reservation."

[definitions.IpAddressReservation-response.properties.tags]
type = "array"
description = "Tags associated with the object."

[definitions.IpAddressReservation-response.properties.uri]
type = "string"
description = "Uniform Resource Identifier"

[paths."/network/v1/ipreservation/".post.responses.201]
description = "Created. See <a class=\"xref\" href=\"Status%20Codes.html\">Status Codes</a> for information about other possible HTTP status codes."

[paths."/network/v1/ipreservation/{container}/".get.responses.200]
description = "OK. See <a class=\"xref\" href=\"Status%20Codes.html\">Status Codes</a> for information about other possible HTTP status codes."

[paths."/network/v1/ipreservation/{name}".put.responses.200]
description = "OK. See <a class=\"xref\" href=\"Status%20Codes.html\">Status Codes</a> for information about other possible HTTP status codes."

[paths."/network/v1/ipreservation/{name}".delete.responses.204]
description = "No Content. See <a class=\"xref\" href=\"Status%20Codes.html\">Status Codes</a> for information about other possible HTTP status codes."

[paths."/network/v1/ipreservation/{name}".get.responses.200]
description = "OK. See <a class=\"xref\" href=\"Status%20Codes.html\">Status Codes</a> for information about other possible HTTP status codes."

[definitions.IpAddressReservation-list-response.properties.result.items]
"$ref" = "#/definitions/IpAddressReservation-response"

[definitions.IpAddressReservation-post-request.properties.tags.items]
type = "string"

[definitions.IpAddressReservation-put-request.properties.tags.items]
type = "string"

[definitions.IpAddressReservation-response.properties.tags.items]
type = "string"

[paths."/network/v1/ipreservation/".post.responses.201.schema]
"$ref" = "#/definitions/IpAddressReservation-response"

[paths."/network/v1/ipreservation/{container}/".get.responses.200.schema]
"$ref" = "#/definitions/IpAddressReservation-list-response"

[paths."/network/v1/ipreservation/{name}".put.responses.200.schema]
"$ref" = "#/definitions/IpAddressReservation-response"

[paths."/network/v1/ipreservation/{name}".get.responses.200.schema]
"$ref" = "#/definitions/IpAddressReservation-response"

[paths."/network/v1/ipreservation/".post.responses.201.headers.set-cookie]
type = "string"
description = "The cookie value is returned if the session is extended"

[paths."/network/v1/ipreservation/{container}/".get.responses.200.headers.set-cookie]
type = "string"
description = "The cookie value is returned if the session is extended"

[paths."/network/v1/ipreservation/{name}".put.responses.200.headers.set-cookie]
type = "string"
description = "The cookie value is returned if the session is extended"

[paths."/network/v1/ipreservation/{name}".delete.responses.204.headers.set-cookie]
type = "string"
description = "The cookie value is returned if the session is extended"

[paths."/network/v1/ipreservation/{name}".get.responses.200.headers.set-cookie]
type = "string"
description = "The cookie value is returned if the session is extended"
