consumes:
- application/oracle-compute-v3+json
- application/oracle-compute-v3+directory+json
definitions:
    Account-discover-response:
        properties:
            result:
                items:
                    type: string
                type: array
    Account-list-response:
        properties:
            result:
                items:
                    $ref: '#/definitions/Account-response'
                type: array
    Account-response:
        properties:
            accounttype:
                description: Account Type for this account
                type: string
            credentials:
                additionalProperties:
                    type: object
                description: Credentials specific to the account, which may include
                    a username, password or certificate. The credentials are not returned.
                type: object
            description:
                description: Description of this account.
                type: string
            name:
                description: 'Two-part name of the account: <code>/Compute-<em>identity_domain</em>/default</code>
                    or <code>/Compute-<em>identity_domain</em>/cloud_storage</code>'
                type: string
            objectproperties:
                additionalProperties:
                    type: object
                description: Properties to be applied to specific objects created
                    using this account
                type: object
            uri:
                description: Uniform Resource Identifier
                type: string
    DailyWeeklyInterval:
        allOf:
        -   $ref: '#/definitions/Interval'
        -   description: Backup Interval running once a day on certain days of the
                week
            properties:
                daysOfWeek:
                    description: Days of the week to run a backup
                    items:
                        enum:
                        - MONDAY
                        - TUESDAY
                        - WEDNESDAY
                        - THURSDAY
                        - FRIDAY
                        - SATURDAY
                        - SUNDAY
                        type: string
                    type: array
                timeOfDay:
                    description: Time of the day to run a backup
                    pattern: ([01]?[0-9]|2[0-3]):[0-5][0-9]
                    type: string
                userTimeZone:
                    description: 'Any IANA time zone. e.g: America/Los_Angeles'
                    type: string
            type: object
    HourlyInterval:
        allOf:
        -   $ref: '#/definitions/Interval'
        -   description: Backup Interval running every X hours
            properties:
                hourlyInterval:
                    description: Hours to wait before starting the next backup
                    format: int32
                    type: integer
            type: object
    Interval:
        description: There are two kinds of Intervals. Each Interval has its own JSON
            format. Your Interval field should look like one of the following:<p><ul><li><code>"interval":{"Hourly":{"hourlyInterval":2}}</code></li><li><code>{"DailyWeekly":{"daysOfWeek":["MONDAY"],"timeOfDay":"03:15","userTimeZone":"America/Los_Angeles"}}</code></li></ul><p>Days
            of the week is any day of the week fully capitalized (MONDAY, TUESDAY,
            etc). The user time zone is any IANA user timezone.  For example user
            time zones see <a href="https://en.wikipedia.org/wiki/IANA_time_zone_database">List
            of IANA time zones</a>.
        type: object
        x-oneOf:
            oneOf:
            -   properties:
                    DailyWeekly:
                        allOf:
                        -   $ref: '#/definitions/DailyWeeklyInterval'
                        -   properties: {}
                            type: object
                type: object
            -   properties:
                    Hourly:
                        allOf:
                        -   $ref: '#/definitions/HourlyInterval'
                        -   properties: {}
                            type: object
                type: object
        x-oneOf-instructions: Provide one of the valid object representations documented
            here.  For more information about oneOf see http://json-schema.org/latest/json-schema-validation.html#anchor88
info:
    description: An account is used in Compute Classic to store credentials that must
        be used to access another service. For example, you use an account to define
        the credentials and other details of the Oracle Cloud Infrastructure Object
        Storage Classic instance in which you store machine images.<p>You can view
        accounts using the HTTP requests listed below.
    title: Accounts
    version: 18.1.2-20180126.052521
paths:
    /account/:
        get:
            consumes:
            - application/oracle-compute-v3+json
            description: 'Retrieves the names of containers that contain objects that
                you can access. You can use this information to construct the multipart
                name of an object.<p><b>Required Role: </b>To complete this task,
                you must have the <code>Compute_Monitor</code> or <code>Compute_Operations</code>
                role. If this role isn''t assigned to you or you''re not sure, then
                ask your system administrator to ensure that the role is assigned
                to you in Oracle Cloud My Services. See <a target="_blank" href="http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6">Modifying
                User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>.'
            operationId: discoverRootAccount
            parameters:
            -   description: 'The Cookie: header must be included with every request
                    to the service. It must be set to the value of the set-cookie
                    header in the response received to the POST /authenticate/ call.'
                in: header
                name: Cookie
                type: string
            produces:
            - application/oracle-compute-v3+directory+json
            responses:
                '200':
                    description: OK. See <a class="xref" href="Status%20Codes.html">Status
                        Codes</a> for information about other possible HTTP status
                        codes.
                    headers:
                        set-cookie:
                            description: The cookie value is returned if the session
                                is extended
                            type: string
                    schema:
                        $ref: '#/definitions/Account-discover-response'
            summary: Retrieve Names of Containers
            tags:
            - Accounts
    /account/{container}:
        get:
            consumes:
            - application/oracle-compute-v3+json
            description: 'Retrieves names of all the accounts in the specified container.<p><b>Required
                Role: </b>To complete this task, you must have the <code>Compute_Monitor</code>
                or <code>Compute_Operations</code> role. If this role isn''t assigned
                to you or you''re not sure, then ask your system administrator to
                ensure that the role is assigned to you in Oracle Cloud My Services.
                See <a target="_blank" href="http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6">Modifying
                User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>.'
            operationId: discoverAccount
            parameters:
            -   description: <p>Specify <code>/Compute-<i>identityDomain</i></code>
                    to retrieve the names of objects that you can access.
                in: path
                name: container
                required: true
                type: string
            -   description: 'The Cookie: header must be included with every request
                    to the service. It must be set to the value of the set-cookie
                    header in the response received to the POST /authenticate/ call.'
                in: header
                name: Cookie
                type: string
            produces:
            - application/oracle-compute-v3+directory+json
            responses:
                '200':
                    description: OK. See <a class="xref" href="Status%20Codes.html">Status
                        Codes</a> for information about other possible HTTP status
                        codes.
                    headers:
                        set-cookie:
                            description: The cookie value is returned if the session
                                is extended
                            type: string
                    schema:
                        $ref: '#/definitions/Account-discover-response'
            summary: Retrieve Names of all Accounts and Subcontainers in a Container
            tags:
            - Accounts
    /account/{container}/:
        get:
            consumes:
            - application/oracle-compute-v3+json
            description: 'Retrieves details of the accounts that are in the specified
                identity domain. You can use this HTTP request to get details of the
                account that you must specify while creating a machine image.<p><b>Required
                Role: </b>To complete this task, you must have the <code>Compute_Monitor</code>
                or <code>Compute_Operations</code> role. If this role isn''t assigned
                to you or you''re not sure, then ask your system administrator to
                ensure that the role is assigned to you in Oracle Cloud My Services.
                See <a target="_blank" href="http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6">Modifying
                User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>.'
            operationId: listAccount
            parameters:
            -   description: '<code>Compute-<em>identity_domain</em></code><p>For
                    example: <code>Compute-acme</code>.'
                in: path
                name: container
                required: true
                type: string
            -   description: 'The Cookie: header must be included with every request
                    to the service. It must be set to the value of the set-cookie
                    header in the response received to the POST /authenticate/ call.'
                in: header
                name: Cookie
                type: string
            produces:
            - application/oracle-compute-v3+json
            responses:
                '200':
                    description: OK. See <a class="xref" href="Status%20Codes.html">Status
                        Codes</a> for information about other possible HTTP status
                        codes.
                    headers:
                        set-cookie:
                            description: The cookie value is returned if the session
                                is extended
                            type: string
                    schema:
                        $ref: '#/definitions/Account-list-response'
            summary: Retrieve Details of all Accounts in a Container
            tags:
            - Accounts
    /account/{name}:
        get:
            consumes:
            - application/oracle-compute-v3+json
            description: 'Retrieves details of the specified account.<p><b>Required
                Role: </b>To complete this task, you must have the <code>Compute_Monitor</code>
                or <code>Compute_Operations</code> role. If this role isn''t assigned
                to you or you''re not sure, then ask your system administrator to
                ensure that the role is assigned to you in Oracle Cloud My Services.
                See <a target="_blank" href="http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=MMOCS-GUID-54C2E747-7D5B-451C-A39C-77936178EBB6">Modifying
                User Roles</a> in <em>Managing and Monitoring Oracle Cloud</em>.'
            operationId: getAccount
            parameters:
            -   description: 'Two-part name of the account: <code>/Compute-<em>identity_domain</em>/default</code>
                    or <code>/Compute-<em>identity_domain</em>/cloud_storage</code>'
                in: path
                name: name
                required: true
                type: string
            -   description: 'The Cookie: header must be included with every request
                    to the service. It must be set to the value of the set-cookie
                    header in the response received to the POST /authenticate/ call.'
                in: header
                name: Cookie
                type: string
            produces:
            - application/oracle-compute-v3+json
            responses:
                '200':
                    description: OK. See <a class="xref" href="Status%20Codes.html">Status
                        Codes</a> for information about other possible HTTP status
                        codes.
                    headers:
                        set-cookie:
                            description: The cookie value is returned if the session
                                is extended
                            type: string
                    schema:
                        $ref: '#/definitions/Account-response'
            summary: Retrieve Details of an Account
            tags:
            - Accounts
produces:
- application/oracle-compute-v3+json
- application/oracle-compute-v3+directory+json
schemes:
- https
swagger: '2.0'
tags:
-   description: An account is used in Compute Classic to store credentials that must
        be used to access another service. For example, you use an account to define
        the credentials and other details of the Oracle Cloud Infrastructure Object
        Storage Classic instance in which you store machine images.<p>You can view
        accounts using the HTTP requests listed below.
    name: Accounts
