# coding: utf-8

"""
    SecRules

    A security rule defines network access over a specified protocol between instances in two security lists, or from a set of external hosts (an IP list) to instances in a security list.<p>Security rules tie the security list, security IP list, and security application entities together.<p>You can create, delete, update, and view security rules using the HTTP requests listed below. For more information about security rules, see <a target=\"_blank\" href=\"http://www.oracle.com/pls/topic/lookup?ctx=stcomputecs&id=STCSG-GUID-1AEDDA2C-3561-4759-B5AD-FB4CD9C2FBD8\">About Security Rules</a> in <em>Using Oracle Cloud Infrastructure Compute Classic</em>.  # noqa: E501

    OpenAPI spec version: 18.1.2-20180126.052521
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sec_rules_api import SecRulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSecRulesApi(unittest.TestCase):
    """SecRulesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sec_rules_api.SecRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_sec_rule(self):
        """Test case for add_sec_rule

        Create a Security Rule  # noqa: E501
        """
        pass

    def test_delete_sec_rule(self):
        """Test case for delete_sec_rule

        Delete a Security Rule  # noqa: E501
        """
        pass

    def test_discover_root_sec_rule(self):
        """Test case for discover_root_sec_rule

        Retrieve Names of Containers  # noqa: E501
        """
        pass

    def test_discover_sec_rule(self):
        """Test case for discover_sec_rule

        Retrieve Names of all Security Rules and Subcontainers in a Container  # noqa: E501
        """
        pass

    def test_get_sec_rule(self):
        """Test case for get_sec_rule

        Retrieve Details of a Security Rule  # noqa: E501
        """
        pass

    def test_list_sec_rule(self):
        """Test case for list_sec_rule

        Retrieve Details of all Security Rules in a Container  # noqa: E501
        """
        pass

    def test_update_sec_rule(self):
        """Test case for update_sec_rule

        Update a Security Rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
