#!/usr/bin/env python
# Copyright (c) 2015 Oracle and/or its affiliates. All rights reserved.
# created by sahit.gollapudi

""" Oracle Public Cloud CLI main runner script """

import sys

def main():
    #import opaascli.opccli
    try:
        from opaascli import opccli
        return opccli.main()
    except ImportError as e:
        print("'psm' command not found. Please check and update PATH environment variable with the correct Python installation file_path.")

if __name__ == '__main__':

     req_version = (3,3)
     cur_version = sys.version_info

     if cur_version >= req_version:
        main()
     else:
        print("")
        print("")
        print("Please upgrade Python to version 3.3+. If already on 3.3+ version,")
        print("please update the PATH environment variable with the correct Python installation file_path.")
        print("")

