[iaas_classic.open_api_spec_catalog]
api_catalog_name = 'iaas_classic'
name = 'Oracle Cloud Infrastructure Compute Classic'
api_version = '18.1.2'
descr = 'Use the Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources.'
spec_url = 'https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/compute/{{api_version}}/apis/{{service_name}}/canonical'
spec_files_dir = 'iaas_classic'
spec_file_name = '{{service_name | lower}}.json'
pretty_spec_file_name = '{{service_name | lower}}_{{api_version}}_pretty.json'
yaml_spec_file_name = '{{service_name | lower}}_{{api_version}}.yaml'
toml_spec_file_name = '{{service_name | lower}}_{{api_version}}.toml'
api_doc_url = 'https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stcsa/api-instances.html'
swagger_ui2_url = 'https://apicatalog.oraclecloud.com/ui/views/apicollection/oracle-public/compute/{{api_version}}/{{service_name}}'
swagger_ui3_url = 'https://apicatalog.oraclecloud.com/ui/views/swaggerui3/oracle-public/compute/{{api_version}}?urls.primaryName={{service_name}}'
swagger_ui2_furl: fstr = 'https://apicatalog.oraclecloud.com/ui/views/apicollection/oracle-public/compute/{api_version}/{service_name}'
swagger_ui3_furl: fstr = 'https://apicatalog.oraclecloud.com/ui/views/swaggerui3/oracle-public/compute/{api_version}?urls.primaryName={service_name}'

[iaas_classic.open_api_spec_catalog.open_api_spec_overlays]
schemes = ['https']

[iaas_classic.open_api_spec_catalog.open_api_spec_deletions]
schemes = ['http']
