[iaas_classic.open_api_specs]
__doc__ = "API Specs"
open_api_spec_base: Path = 'etc/open_api'
name  = 'iaas_classic'
descr = "Oracle Cloud Infrastructure Compute Classic REST API to provision and manage instances and the associated resources."
file_format = 'yaml'


