[iaas_classic.services]

[iaas_classic.services.rest_endpoints]


[iaas_classic.services.compute.Instances]
api_collection_name = 'compute'
name = 'Instances'
service_name = 'Instances'
title = 'Instances'
api_version = '18.1.2'


[iaas_classic.services.compute.SecRules]
api_collection_name = 'compute'
name = 'SecRules'
service_name = 'SecRules'
title = "SecRules"
api_version = '18.1.2'

[iaas_classic.services.compute.SecApplications]
api_collection_name = 'compute'
name = 'SecApplications'
service_name = 'SecApplications'
title = "SecApplications"
api_version = '18.1.2'

