[iaas_classic.services]


[iaas_classic.services.Instances]
name = 'Instances'
title = 'Instances'
api_collection_name = 'compute'
api_version = '18.1.2'


[iaas_classic.services.SecRules]
name = 'SecRules'
title = "SecRules"
api_collection_name = 'compute'
api_version = '18.1.2'

[iaas_classic.services.SecApplications]
name = 'SecApplications'
title = "SecApplications"
api_collection_name = 'compute'
api_version = '18.1.2'

