[iaas_classic.services]
spec_url = 'https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/compute/{{iaas_classic.api_catalog.api_version}}/apis/{{service_name}}/canonical'
spec_file = '{{service_name | lower}}{{iaas_classic.api_catalog.api_version}}.json'


[iaas_classic.services.Instances]
service_name = 'Instances'
api_version = '18.1.2'
name = 'Instances'
spec_url = 'https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/compute/18.1.2/apis/Instances/canonical'
spec_furl: fstr = 'https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/compute/{api_version}/apis/{service_name}/canonical'
spec_file = 'Instances.json'
api_doc_url = 'https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stcsa/api-instances.html'
swagger_ui2_url = 'https://apicatalog.oraclecloud.com/ui/views/apicollection/oracle-public/compute/18.1.2/Instances'
swagger_ui3_url = 'https://apicatalog.oraclecloud.com/ui/views/swaggerui3/oracle-public/compute/18.1.2?urls.primaryName=Instances'
swagger_ui2_furl: fstr = 'https://apicatalog.oraclecloud.com/ui/views/apicollection/oracle-public/compute/{api_version}/{service_name}'
swagger_ui3_furl: fstr = 'https://apicatalog.oraclecloud.com/ui/views/swaggerui3/oracle-public/compute/{api_version}?urls.primaryName={service_name}'


[iaas_classic.services.SecurityRules]
service_name = 'SecurityRules'
name = 'SecurityRules'
api_version = '18.1.2'
spec_url = 'https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/compute/18.1.2/apis/SecurityRules/canonical'
spec_furl: fstr = 'https://apicatalog.oraclecloud.com/public/v1/orgs/oracle-public/apicollections/compute/{api_version}/apis/{service_name}/canonical'
spec_file = 'SecurityRules.json'
api_doc_url = 'https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stcsa/api-security-rules.html'
swagger_ui2_url = 'https://apicatalog.oraclecloud.com/ui/views/apicollection/oracle-public/compute/18.1.2/Instances'
swagger_ui3_url = 'https://apicatalog.oraclecloud.com/ui/views/swaggerui3/oracle-public/compute/18.1.2?urls.primaryName=SecurityRules'
swagger_ui2_furl: fstr = 'https://apicatalog.oraclecloud.com/ui/views/apicollection/oracle-public/compute/{api_version}/{service_name}'
swagger_ui3_furl: fstr = 'https://apicatalog.oraclecloud.com/ui/views/swaggerui3/oracle-public/compute/{api_version}?urls.primaryName={service_name}'






