[user]
first_name = 'Eric'
last_name = 'Harris'
email = 'eric.harris@oracle.com'
cloud_username = 'eric.harris@oracle.com'
os_username = 'eharris'
home_directory = 'C:\Users\eharris'
emplid = 12345
is_admin = true
is_fired = false


[user._meta]
title = 'User Information'
file = 'user_info.toml'
decription = 'Basic user information'
dependencies = ''
default_type = 'str'



